// <auto-generated />
using System;
using BusinessObjects.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(HealthCareSystemContext))]
    [Migration("20251119140906_Update Payment")]
    partial class UpdatePayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Domain.Aiconversation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__AIConver__1788CC4C5B86BE7A");

                    b.ToTable("AIConversations", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Domain.Aimessage", b =>
                {
                    b.Property<int>("AimessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AIMessageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AimessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MessageType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AimessageId")
                        .HasName("PK__AIMessag__E8DCEE037413DB0A");

                    b.HasIndex("UserId");

                    b.ToTable("AIMessages", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Domain.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCC2764D6741");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleImg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ArticleId")
                        .HasName("PK__Articles__9C6270E84971FDFE");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BusinessObjects.Domain.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E54864820815F57");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ConversationId")
                        .HasName("PK__Conversa__C050D8773DF32463");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex(new[] { "PatientUserId", "DoctorUserId" }, "UC_Patient_Doctor")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Doctor", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__Doctors__1788CC4C1557C27E");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("BusinessObjects.Domain.MedicalHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId")
                        .HasName("PK__MedicalH__4D7B4ABD8764312C");

                    b.HasIndex("PatientUserId");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("BusinessObjects.Domain.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("TestResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RecordId")
                        .HasName("PK__MedicalR__FBDF78E9AF85EB8E");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C0C9CB551FAD9");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("BMI");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Patients__1788CC4CE1FF4FD2");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("BookingDraftJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A384116471D");

                    b.HasIndex("PatientUserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__Prescrip__40130832ACFEF05A");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientUserId");

                    b.HasIndex("RecordId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CE84982894");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SpecialtyId")
                        .HasName("PK__Specialt__D768F6A85C05BEFF");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("BusinessObjects.Domain.TimeOff", b =>
                {
                    b.Property<int>("TimeOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeOffId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsAllDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("TimeOffId")
                        .HasName("PK__TimeOff__B9CB0CF1BF6A38F0");

                    b.HasIndex("DoctorUserId");

                    b.ToTable("TimeOff", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C15430967");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105347A5BBC04")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessObjects.Domain.WorkingHour", b =>
                {
                    b.Property<int>("WorkingHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkingHoursId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DoctorUserId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsWorking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("WorkingHoursId")
                        .HasName("PK__WorkingH__7576C5B6E2591A2D");

                    b.HasIndex("DoctorUserId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Aiconversation", b =>
                {
                    b.HasOne("BusinessObjects.Domain.User", "User")
                        .WithOne("Aiconversation")
                        .HasForeignKey("BusinessObjects.Domain.Aiconversation", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AIConvers__UserI__19DFD96B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Aimessage", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Aiconversation", "User")
                        .WithMany("Aimessages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AIMessage__UserI__2180FB33");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Appointment", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Doctor", "DoctorUser")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Docto__656C112C");

                    b.HasOne("BusinessObjects.Domain.Patient", "PatientUser")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Patie__66603565");

                    b.Navigation("DoctorUser");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Conversation", b =>
                {
                    b.HasOne("BusinessObjects.Domain.User", "DoctorUser")
                        .WithMany("ConversationDoctorUsers")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__Docto__0C85DE4D");

                    b.HasOne("BusinessObjects.Domain.User", "PatientUser")
                        .WithMany("ConversationPatientUsers")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__Patie__0B91BA14");

                    b.Navigation("DoctorUser");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Doctor", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .HasConstraintName("FK__Doctors__Special__5FB337D6");

                    b.HasOne("BusinessObjects.Domain.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("BusinessObjects.Domain.Doctor", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Doctors__UserId__5EBF139D");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Domain.MedicalHistory", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Patient", "PatientUser")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalHi__Patie__5629CD9C");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.MedicalRecord", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Appointment", "Appointment")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__MedicalRe__Appoi__6D0D32F4");

                    b.HasOne("BusinessObjects.Domain.User", "DoctorUser")
                        .WithMany("MedicalRecordDoctorUsers")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalRe__Docto__6C190EBB");

                    b.HasOne("BusinessObjects.Domain.User", "PatientUser")
                        .WithMany("MedicalRecordPatientUsers")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalRe__Patie__6B24EA82");

                    b.Navigation("Appointment");

                    b.Navigation("DoctorUser");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Message", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Conver__1332DBDC");

                    b.HasOne("BusinessObjects.Domain.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Sender__14270015");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Patient", b =>
                {
                    b.HasOne("BusinessObjects.Domain.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("BusinessObjects.Domain.Patient", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Patients__UserId__534D60F1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Payment", b =>
                {
                    b.HasOne("BusinessObjects.Domain.User", "PatientUser")
                        .WithMany("Payments")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Patien__787EE5A0");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Prescription", b =>
                {
                    b.HasOne("BusinessObjects.Domain.User", "DoctorUser")
                        .WithMany("PrescriptionDoctorUsers")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Docto__73BA3083");

                    b.HasOne("BusinessObjects.Domain.User", "PatientUser")
                        .WithMany("PrescriptionPatientUsers")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Patie__72C60C4A");

                    b.HasOne("BusinessObjects.Domain.MedicalRecord", "Record")
                        .WithMany("Prescriptions")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Recor__71D1E811");

                    b.Navigation("DoctorUser");

                    b.Navigation("PatientUser");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Review", b =>
                {
                    b.HasOne("BusinessObjects.Domain.User", "DoctorUser")
                        .WithMany("ReviewDoctorUsers")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__DoctorU__02FC7413");

                    b.HasOne("BusinessObjects.Domain.User", "PatientUser")
                        .WithMany("ReviewPatientUsers")
                        .HasForeignKey("PatientUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Patient__02084FDA");

                    b.Navigation("DoctorUser");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.TimeOff", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Doctor", "DoctorUser")
                        .WithMany("TimeOffs")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__TimeOff__DoctorU__2CF2ADDF");

                    b.Navigation("DoctorUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.WorkingHour", b =>
                {
                    b.HasOne("BusinessObjects.Domain.Doctor", "DoctorUser")
                        .WithMany("WorkingHours")
                        .HasForeignKey("DoctorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__WorkingHo__Docto__2739D489");

                    b.Navigation("DoctorUser");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Aiconversation", b =>
                {
                    b.Navigation("Aimessages");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Appointment", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TimeOffs");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BusinessObjects.Domain.MedicalRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalHistories");
                });

            modelBuilder.Entity("BusinessObjects.Domain.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("BusinessObjects.Domain.User", b =>
                {
                    b.Navigation("Aiconversation");

                    b.Navigation("ConversationDoctorUsers");

                    b.Navigation("ConversationPatientUsers");

                    b.Navigation("Doctor");

                    b.Navigation("MedicalRecordDoctorUsers");

                    b.Navigation("MedicalRecordPatientUsers");

                    b.Navigation("Messages");

                    b.Navigation("Patient");

                    b.Navigation("Payments");

                    b.Navigation("PrescriptionDoctorUsers");

                    b.Navigation("PrescriptionPatientUsers");

                    b.Navigation("ReviewDoctorUsers");

                    b.Navigation("ReviewPatientUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
